## Numpy aaray

In [54]:
import numpy as np

zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
arr_1d = np.array([1,3,4,56])
print(arr_1d)

[ 1  3  4 56]


In [56]:
py_list = [1,2,5]
print("the pyhton list multiplication is : " , py_list*3)

the pyhton list multiplication is :  [1, 2, 5, 1, 2, 5, 1, 2, 5]


In [57]:
np_array = np.array([1,4,5,6])
print("the numpy array multiplication is :" , np_array*3)

the numpy array multiplication is : [ 3 12 15 18]


In [58]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [59]:
random = np.random.random((2,1))
print(random)

sequence = np.arange(2,4)
print(sequence)

[[0.58228927]
 [0.77245749]]
[2 3]


###vector,matrix and tensor

In [60]:
vector=np.array([1,2,3])
print(vector)

matrix= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)



[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**ARRAY PROPERTIES**

In [ ]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array)
print("size :" , array.size)//total number of elements
print("dimension :",array.ndim)
print("shape: ",array.shape)
print("data type: ",array.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
size : 9
dimension : 2
shape:  (3, 3)
data type:  int64


***reshaping of array***

In [69]:
arr=np.arange(15)
print(arr)

reshape = arr.reshape(5,3)
print("\nreshape:", reshape)

flattend = reshape.flatten()
print("\nflatend:" , flattend)


#ravel(returns view , instead of copy)
raveled = reshape.ravel()
print("\nraveled:",raveled)


transpose = reshape.T
print("\ntranspose:", transpose)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

reshape: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

flatend: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

transpose: [[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
