****numpy array operations****

In [5]:
import numpy as np

In [ ]:
arr =np.arange(12)
print(arr)
print("Basic Slicing: ",arr[2:6])
print("with step :" , arr[1:8:2])
print("negative indexing :" ,arr[-7])
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Basic Slicing:  [2 3 4 5]
with step : [1 3 5 7]
negative indexing : 5


In [ ]:
arr_2d = np.array([[1,3,5],
                   [8,4,3],
                   [5,8,2]])
print(arr_2d)
print("elements :", arr_2d[2,1])//2nd row ka 1st column


[[1 3 5]
 [8 4 3]
 [5 8 2]]
elements : 8


***Sorting***

In [ ]:
unsorted = np.array([5, 2,3,5,4, 9, 1, 5, 6])
print("sorted array :" , np.sort(unsorted))


arr_2d = np.array([[1,3,5],[2,5,7],[7,1,2]])
print("sorted 2d_array by column :", np.sort(arr_2d , axis=0))//sort by column
print("sorted 2d_array by row :", np.sort(arr_2d , axis=1)) //sort by row

sorted array : [1 2 3 4 5 5 5 6 9]
sorted 2d_array by column : [[1 1 2]
 [2 3 5]
 [7 5 7]]
sorted 2d_array by row : [[1 3 5]
 [2 5 7]
 [1 2 7]]


***Fancy indexing vs np.where()***