**adding and removing element**

In [1]:
import numpy as np

In [3]:
arr_1 = np.array([2,4,5,6,3])
arr_2 = np.array([4,1,5,8,3])
combined = np.concatenate((arr_1,arr_2))
print("combined array :", combined) 

combined array : [2 4 5 6 3 4 1 5 8 3]





*******array compatibility*******

In [6]:
a= np.array([1,4,55])
b= np.array([4,2,5,4])
c= np.array([5,6,7])

print("compatibilty test :", a.shape == b.shape == c.shape)

compatibilty test : False


In [9]:
original = np.array([[2,3,4],[4,7,6]])
new = np.array([2,4,5])

with_new_row = np.vstack((original,new))
print("array after adding new row :", with_new_row)

new_col = np.array([[2],[4]])
with_new_col = np.hstack((original,new_col))
print("array after adding new column :", with_new_col)

array after adding new row : [[2 3 4]
 [4 7 6]
 [2 4 5]]
array after adding new column : [[2 3 4 2]
 [4 7 6 4]]


In [10]:
arr1 = np.array([1,2,3,4,5,6])
deleted_element = np.delete(arr1,2)
print("array after deleting element :", deleted_element)

array after deleting element : [1 2 4 5 6]
